# Generated by Django 3.0 on 2020-01-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('data_encerramento', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_unid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_insercao', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.Mesa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='produtos',
            field=models.ManyToManyField(related_name='mesa_produtos', to='vendas.Produto'),
        ),
    ]
