version: '3.4'

services:
  app:
    image: espetaria
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker123
    ports:
        - 5432:5432