# Generated by Django 3.0 on 2019-12-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_unid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_insercao', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('at', 'ativo'), ('ex', 'deletado')], default='at', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'produtos',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('on', 'ativa'), ('of', 'fechada')], default='on', max_length=2)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.produto')),
            ],
            options={
                'verbose_name_plural': 'vendas',
                'db_table': 'venda',
            },
        ),
    ]
